markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/PRD.md
  prdVersion: v4
  prdSharded: false
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/ARCH.md
  architectureVersion: v4
  architectureSharded: false
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/ARCH.md
devDebugLog: .ai/debug-log.md
devStoryLocation: stories
slashPrefix: BMad
